apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: kouma-adv-daba-26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: assagnon/my-java-app:latest
          imagePullPolicy: Always
          env:
            - name: MAX_NODES
              value: "50000"
            - name: JSON_FILE
              value: "http://vmrum.isc.heia-fr.ch/files/DBLP-Citation-network-V18.jsonl"
            - name: NEO4J_IP
              value: "neo4j-service.kouma-adv-daba-26.svc.cluster.local"

