services:
  db:
    image: neo4j:4.4.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      internal:
        ipv4_address: 172.31.0.10
    volumes:
      - ./neo4j_mount/data:/data
      - ./neo4j_mount/logs:/logs
      - ./neo4j_mount/conf:/conf
    environment:
      - NEO4J_AUTH=neo4j/test
    deploy:
      resources:
        limits:
          memory: 3g

  app:
    image: neo4jtp:latest
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - ./dblpExample.jsonl:/file.jsonl
    environment:
      - JSON_FILE=/file.jsonl
      - MAX_NODES=10000
      - NEO4J_IP=172.31.0.10
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.31.0.0/24"